ALTER TYPE "OrigemChamado" ADD VALUE IF NOT EXISTS 'EMAIL';

ALTER TABLE "intencoes"
ADD COLUMN IF NOT EXISTS "canais" TEXT[] NOT NULL DEFAULT ARRAY['MANUAL', 'SIMULADOR', 'WHATSAPP', 'EMAIL']::TEXT[];
